# CDAW CME Catalog Merge To LASCO Catalog
This notebook is for creating a merged CME catalog (which contains filenames).

In [1]:
import requests
import pandas as pd

Need_To_Redownload = False
CDAW_Catalog_Filename = '../cdaw_catalog.txt'
LASCO_Catalog_Filename = '../lasco_img_catalog_lvl_1.txt'
CME_Catalog_Filename = '../cme_event_catlog.txt'

In [2]:
# pull the lasco catalog to local disk
if Need_To_Redownload:
    
    # download LASCO catalog now
    lasco_hdr_url = 'https://lasco-www.nrl.navy.mil/lz/img_hdr.txt'
    response = requests.get(lasco_hdr_url, allow_redirects=True)
    
    # cache locally
    open(LASCO_Catalog_Filename, 'wb').write(response.content)

In [3]:
cme_data = pd.read_csv(CME_Catalog_Filename)
cme_data = cme_data.rename(columns={'Unnamed: 0':'CDAW_Id'})
cme_data

,CDAW_Id,Date,Time,Central,Width,Linear,2nd,order,speed,Accel,Mass,Kinetic,MPA,Remarks,Duration_C2,Duration_C3,StartTime_C3_Delta
0,5,1996/01/31,06:52:13,274,47,158,219,99,0,-12.3*,2.5e+14*,3.2e+28*,272,Poor Event; Only 3 points\n,26582.278481,116518.987342,9746.835443
1,8,1996/02/12,05:47:26,91,53,160,100,211,236,2.0*,1.3e+15,1.6e+29,92,Poor Event\n,26250.000000,115062.500000,9625.000000
2,12,1996/03/02,04:11:53,88,36,108,95,120,177,1.0*,1.5e+14,8.7e+27,86,Poor Event\n,38888.888889,170462.962963,14259.259259
3,16,1996/03/07,07:51:56,91,43,60,60,61,75,0.1*,-------,-------,87,Poor Event\n,70000.000000,306833.333333,25666.666667
4,18,1996/03/09,04:27:49,84,39,93,102,82,0,-1.1*,-------,-------,82,Only 3 points\n,45161.290323,197956.989247,16559.139785
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7573,30303,2020/05/26,00:36:06,255,95,142,75,216,289,3.2*,-------,-------,251,Poor Event\n,29577.464789,129647.887324,10845.070423
7574,30304,2020/05/26,10:36:05,242,36,172,159,185,271,2.0*,-------,-------,262,Poor Event\n,24418.604651,107034.883721,8953.488372
7575,30306,2020/05/27,06:00:06,83,17,108,89,129,222,1.8*,-------,-------,89,Poor Event\n,38888.888889,170462.962963,14259.259259
7576,30312,2020/05/28,03:12:09,87,19,173,132,217,406,6.6*,-------,-------,87,Poor Event\n,24277.456647,106416.184971,8901.734104
7577,30314,2020/05/28,21:12:11,260,23,187,183,192,214,0.5*,-------,-------,258,Poor Event\n,22459.893048,98449.197861,8235.294118

In [4]:
# now work to merge in information from LASCO img catalog
lasco_catalog = pd.read_fwf(LASCO_Catalog_Filename, index=False,
                            names=['filename', 'date-obs', 'time-obs','telescope', 'expTime',
                                   'NumCols', 'NumRows', 'StartCol', 'StartRow', 'Filter', 
                                   'Polarizer','Observ.Seq', 'LEB Program', 'junk'])

In [5]:
lasco_catalog

,filename,date-obs,time-obs,telescope,expTime,NumCols,NumRows,StartCol,StartRow,Filter,Polarizer,Observ.Seq,LEB Program,junk
0,35000706.fts,1996/01/11,22:54:31,C3,3.8,128,128,469,297,Clear,Clear,XZR,0.2298,0
1,35000707.fts,1996/01/11,23:00:29,C3,3.1,512,512,277,275,Clear,Clear,XZR,0.2298,0
2,35000708.fts,1996/01/11,23:15:34,C3,15.1,512,256,277,403,Clear,Clear,XZR,0.2298,0
3,35002640.fts,1996/01/16,00:58:18,C3,19.1,1024,1024,20,1,Clear,Clear,XZR,0.2298,0
4,35002645.fts,1996/01/16,02:10:12,C3,19.1,1024,1024,20,1,Clear,Clear,XZR,0.2298,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913203,35513587.fts,2017/08/31,23:28:54,C3,17.9,1024,1024,20,1,Clear,Clear,XZR,0.7160,0
913204,25649103.fts,2017/08/31,23:34:50,C2,25.1,1024,1024,20,1,Orang,Clear,XZ%,1.4430,0
913205,35513588.fts,2017/08/31,23:40:50,C3,17.6,1024,1024,20,1,Clear,Clear,XZR,0.7150,0
913206,25649104.fts,2017/08/31,23:46:51,C2,25.1,1024,1024,20,1,Orang,Clear,XZ%,1.4400,0
913207,35513589.fts,2017/08/31,23:52:50,C3,17.9,1024,1024,20,1,Clear,Clear,XZR,0.7140,0

In [6]:
# Drop C1, EIT observations (this speeds up datetime calc below)
lasco_catalog = lasco_catalog[lasco_catalog['telescope'] != 'C1']
lasco_catalog = lasco_catalog[lasco_catalog['telescope'] != 'EIT']

#date_filt = lasco_catalog[lasco_catalog['date-obs']=='2020/05/28']
#date_filt[date_filt['time-obs']=='21:12:11']
len(lasco_catalog)

913208

In [7]:
from datetime import datetime, date, time, timezone, timedelta

# add column of python datetime for easier handling
datetime_col = []
for row in lasco_catalog.iterrows():
    date_obs = row[1]['date-obs']
    time_obs = row[1]['time-obs']
    
    date_obs = [int(t) for t in row[1]['date-obs'].split('/')]
    time_obs = [int(t) for t in row[1]['time-obs'].split(':')]
    
    datetime_col.append(datetime(year=date_obs[0], month=date_obs[1], day=date_obs[2], hour=time_obs[0], minute=time_obs[1], second=time_obs[2]))

lasco_catalog['datetime'] = datetime_col
lasco_catalog

,filename,date-obs,time-obs,telescope,expTime,NumCols,NumRows,StartCol,StartRow,Filter,Polarizer,Observ.Seq,LEB Program,junk,datetime
0,35000706.fts,1996/01/11,22:54:31,C3,3.8,128,128,469,297,Clear,Clear,XZR,0.2298,0,1996-01-11 22:54:31
1,35000707.fts,1996/01/11,23:00:29,C3,3.1,512,512,277,275,Clear,Clear,XZR,0.2298,0,1996-01-11 23:00:29
2,35000708.fts,1996/01/11,23:15:34,C3,15.1,512,256,277,403,Clear,Clear,XZR,0.2298,0,1996-01-11 23:15:34
3,35002640.fts,1996/01/16,00:58:18,C3,19.1,1024,1024,20,1,Clear,Clear,XZR,0.2298,0,1996-01-16 00:58:18
4,35002645.fts,1996/01/16,02:10:12,C3,19.1,1024,1024,20,1,Clear,Clear,XZR,0.2298,0,1996-01-16 02:10:12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913203,35513587.fts,2017/08/31,23:28:54,C3,17.9,1024,1024,20,1,Clear,Clear,XZR,0.7160,0,2017-08-31 23:28:54
913204,25649103.fts,2017/08/31,23:34:50,C2,25.1,1024,1024,20,1,Orang,Clear,XZ%,1.4430,0,2017-08-31 23:34:50
913205,35513588.fts,2017/08/31,23:40:50,C3,17.6,1024,1024,20,1,Clear,Clear,XZR,0.7150,0,2017-08-31 23:40:50
913206,25649104.fts,2017/08/31,23:46:51,C2,25.1,1024,1024,20,1,Orang,Clear,XZ%,1.4400,0,2017-08-31 23:46:51
913207,35513589.fts,2017/08/31,23:52:50,C3,17.9,1024,1024,20,1,Clear,Clear,XZR,0.7140,0,2017-08-31 23:52:50

In [8]:
#merge data, using CME events for lookup of filename.

cme_ids=[]
filenames=[]
filters = []
dates=[]
times=[]

lasco_keepCols = ['filename', 'telescope', 'NumCols', 'NumRows', 'Filter', 'Polarizer', 'datetime', 'expTime']
cdaw_keepCols = ['Remarks', 'Central', 'Width', 'Linear', 'CDAW_Id']

merged_data = {  col:[] for col in lasco_keepCols + cdaw_keepCols}

# split up catalog by C2 and C3
c2_lasco = lasco_catalog[lasco_catalog['telescope']=='C2']
c3_lasco = lasco_catalog[lasco_catalog['telescope']=='C3']

for event in cme_data.iterrows():
    
    # grab date-time-duration info for our event
    cme_start_date = [int(t) for t in event[1]['Date'].split('/')]
    cme_start_time = [int(t) for t in event[1]['Time'].split(':')]
    cme_c3_delta = timedelta(seconds=event[1]['StartTime_C3_Delta'])
    cme_c2_duration = timedelta(seconds=float(event[1]['Duration_C2']))
    cme_c3_duration = timedelta(seconds=float(event[1]['Duration_C3']))
    
    # convert to Python datetime for easier slicing
    cme_date = date (year=cme_start_date[0], month=cme_start_date[1], day=cme_start_date[2])
    cme_time = time(hour=cme_start_time[0],minute=cme_start_time[1],second=cme_start_time[2])
    
    c2_start = datetime.combine(cme_date,cme_time)
    c2_end   = c2_start + cme_c2_duration
    
    c3_start = c2_start + cme_c3_delta
    c3_end   = c3_start + cme_c3_duration
    
    # get C2 entries
    c2_slice = c2_lasco[c2_lasco['datetime']>c2_start]
    for lasco_row in c2_slice[c2_slice['datetime']<=c2_end].iterrows():
        
        for col in lasco_keepCols:
            merged_data[col].append(lasco_row[1][col])
          
        for col in cdaw_keepCols:
            merged_data[col].append(event[1][col])
                
    # get C3 entries
    c3_slice = c3_lasco[c3_lasco['datetime']>c3_start]
    for lasco_row in c3_slice[c3_slice['datetime']<=c3_end].iterrows():
        
        for col in lasco_keepCols:
            merged_data[col].append(lasco_row[1][col])
          
        for col in cdaw_keepCols:
            merged_data[col].append(event[1][col])
                

# convert results to DataFrame
result = pd.DataFrame(merged_data)
result

,filename,telescope,NumCols,NumRows,Filter,Polarizer,datetime,expTime,Remarks,Central,Width,Linear,CDAW_Id
0,25000294.fts,C2,1024,1024,Orang,Clear,1996-01-31 08:01:38,25.4,Poor Event; Only 3 points\n,274,47,158,5
1,25000295.fts,C2,1024,1024,Orang,Clear,1996-01-31 09:11:14,25.0,Poor Event; Only 3 points\n,274,47,158,5
2,25000296.fts,C2,1024,1024,Orang,Clear,1996-01-31 10:20:39,25.0,Poor Event; Only 3 points\n,274,47,158,5
3,25000297.fts,C2,1024,1024,Orang,Clear,1996-01-31 11:30:19,25.9,Poor Event; Only 3 points\n,274,47,158,5
4,25000298.fts,C2,1024,1024,Orang,Clear,1996-01-31 12:40:17,25.1,Poor Event; Only 3 points\n,274,47,158,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
398826,35513585.fts,C3,1024,1024,Clear,Clear,2017-08-31 23:04:45,17.6,Poor Event\n,275,54,274,28858
398827,35513586.fts,C3,1024,1024,Clear,Clear,2017-08-31 23:16:36,17.5,Poor Event\n,275,54,274,28858
398828,35513587.fts,C3,1024,1024,Clear,Clear,2017-08-31 23:28:54,17.9,Poor Event\n,275,54,274,28858
398829,35513588.fts,C3,1024,1024,Clear,Clear,2017-08-31 23:40:50,17.6,Poor Event\n,275,54,274,28858
398830,35513589.fts,C3,1024,1024,Clear,Clear,2017-08-31 23:52:50,17.9,Poor Event\n,275,54,274,28858

In [9]:
result.to_csv('../merged_cdaw_lasco_catalog.csv')

In [10]:
# test it out, try to pull a few intervals for events
C2_data = result[result['telescope']=='C2']
C2_data

,filename,telescope,NumCols,NumRows,Filter,Polarizer,datetime,expTime,Remarks,Central,Width,Linear,CDAW_Id
0,25000294.fts,C2,1024,1024,Orang,Clear,1996-01-31 08:01:38,25.4,Poor Event; Only 3 points\n,274,47,158,5
1,25000295.fts,C2,1024,1024,Orang,Clear,1996-01-31 09:11:14,25.0,Poor Event; Only 3 points\n,274,47,158,5
2,25000296.fts,C2,1024,1024,Orang,Clear,1996-01-31 10:20:39,25.0,Poor Event; Only 3 points\n,274,47,158,5
3,25000297.fts,C2,1024,1024,Orang,Clear,1996-01-31 11:30:19,25.9,Poor Event; Only 3 points\n,274,47,158,5
4,25000298.fts,C2,1024,1024,Orang,Clear,1996-01-31 12:40:17,25.1,Poor Event; Only 3 points\n,274,47,158,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
398791,25649074.fts,C2,1024,1024,Orang,Clear,2017-08-31 18:11:10,25.1,Poor Event\n,275,54,274,28858
398792,25649075.fts,C2,1024,1024,Orang,Clear,2017-08-31 18:23:08,25.3,Poor Event\n,275,54,274,28858
398793,25649076.fts,C2,1024,1024,Orang,Clear,2017-08-31 18:35:08,25.1,Poor Event\n,275,54,274,28858
398794,25649077.fts,C2,1024,1024,Orang,Clear,2017-08-31 18:47:07,25.1,Poor Event\n,275,54,274,28858
398795,25649078.fts,C2,1024,1024,Orang,Clear,2017-08-31 18:59:05,25.1,Poor Event\n,275,54,274,28858